import js from '@eslint/js';
import globals from 'globals';
import prettier from 'eslint-config-prettier';

export default [
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      // Vendored third-party code.
      'src/trello-power-up/soundtouch-worklet.js',
      // Generated by scripts/build-popup.mjs.
      'src/trello-power-up/trello-player-power-up-popup.js'
    ]
  },
  js.configs.recommended,
  {
    files: ['src/trello-power-up/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        WaveSurfer: 'readonly'
      }
    }
  },
  {
    // Classic (non-module) scripts loaded directly by the HTML pages.
    files: ['src/trello-power-up/trello-player-power-up.js', 'src/trello-power-up/trello-player-config.js'],
    languageOptions: {
      sourceType: 'script'
    }
  },
  {
    files: ['src/cloudflare-worker-cors-proxy/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: globals.serviceworker
    }
  },
  {
    files: ['scripts/**/*.mjs', 'test/**/*.js', 'eslint.config.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: globals.node
    }
  },
  prettier
];
